trigger:
  branches:
    include:
    - master
    - 'validate/*'
    - 'release/*'
  paths:
    exclude:
    - doc/
    - '*.md'
    - .vscode/
    - .github/

variables:
  TreatWarningsAsErrors: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  codecov_token: 5e413578-757f-4178-8a3f-fa3f1ca0c2b2
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages
  
jobs:
- template: azure-pipelines/build.yml